# Generated by Django 5.2.16 on 2026-07-28 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('name_fa', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('slug_fa', models.SlugField(allow_unicode=True, unique=True)),
                ('slug_en', models.SlugField(unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('excerpt_fa', models.TextField(blank=True, default='')),
                ('excerpt_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reading_time_fa', models.IntegerField(default=0)),
                ('reading_time_en', models.IntegerField(default=0)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='media.mediaasset')),
                ('topics', models.ManyToManyField(blank=True, related_name='articles', to='blog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=2)),
                ('block_type', models.CharField(max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('ordering', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.article')),
            ],
            options={
                'ordering': ['ordering'],
                'unique_together': {('article', 'locale', 'ordering')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug_fa'], name='blog_articl_slug_fa_299a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug_en'], name='blog_articl_slug_en_5e8df1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='blog_articl_status_57fc64_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='blog_articl_publish_cc3c64_idx'),
        ),
    ]
