# Generated by Django 5.2.16 on 2026-08-10 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('locale', models.CharField(default='fa-IR', max_length=10)),
                ('direction', models.CharField(default='rtl', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuilderPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('schema', models.JSONField(help_text='Immutable snapshot of the page document schema.')),
                ('schema_version', models.CharField(default='1.0.0', max_length=32)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', help_text="Why this version was created (e.g., 'publish', 'checkpoint').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.builderpage')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='builderpage',
            name='current_published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.builderpageversion'),
        ),
        migrations.CreateModel(
            name='BuilderPageDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField(default=dict, help_text='Full page document schema (JSONB). Source of Truth.')),
                ('revision', models.PositiveBigIntegerField(default=0, help_text='Monotonically increasing revision for optimistic concurrency.')),
                ('schema_version', models.CharField(default='1.0.0', help_text='Schema format version for migrations.', max_length=32)),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of the schema for deduplication.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='pages.builderpage')),
            ],
            options={
                'indexes': [models.Index(fields=['revision'], name='pages_build_revisio_b55c5e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='builderpageversion',
            index=models.Index(fields=['page', 'version_number'], name='pages_build_page_id_02911c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='builderpageversion',
            unique_together={('page', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='builderpage',
            index=models.Index(fields=['slug'], name='pages_build_slug_0885a1_idx'),
        ),
        migrations.AddIndex(
            model_name='builderpage',
            index=models.Index(fields=['status'], name='pages_build_status_1c1ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='builderpage',
            index=models.Index(fields=['published_at'], name='pages_build_publish_6b949c_idx'),
        ),
    ]
