# Generated by Django 5.2.16 on 2026-07-29 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('label_fa', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=2048)),
                ('location', models.CharField(choices=[('header', 'header'), ('footer', 'footer')], max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['location', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('source_path', models.CharField(max_length=2048, unique=True)),
                ('target_url', models.CharField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301'), (302, '302')], default=301)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source_path'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('site_title_fa', models.CharField(max_length=255)),
                ('site_title_en', models.CharField(max_length=255)),
                ('default_title_fa', models.CharField(blank=True, default='', max_length=255)),
                ('default_title_en', models.CharField(blank=True, default='', max_length=255)),
                ('default_description_fa', models.TextField(blank=True, default='')),
                ('default_description_en', models.TextField(blank=True, default='')),
                ('public_email', models.EmailField(blank=True, default='', max_length=254)),
                ('primary_cta_label_fa', models.CharField(blank=True, default='', max_length=100)),
                ('primary_cta_label_en', models.CharField(blank=True, default='', max_length=100)),
                ('primary_cta_url', models.CharField(blank=True, default='', max_length=2048)),
                ('footer_text_fa', models.TextField(blank=True, default='')),
                ('footer_text_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_default_og_images', to='media.mediaasset')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
