# Generated by Django 5.2.16 on 2026-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
