# Generated by Django 5.2.16 on 2026-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_sitesettings_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='density',
            field=models.CharField(default='comfortable', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_preset',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
