# Generated by Django 5.2.16 on 2026-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_sitesettings_density_sitesettings_theme_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='design_tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
