# Generated by Django 5.2.16 on 2026-07-28 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('slug_fa', models.SlugField(allow_unicode=True, unique=True)),
                ('slug_en', models.SlugField(unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('page_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug_fa'], name='cms_page_slug_fa_258a24_idx'), models.Index(fields=['slug_en'], name='cms_page_slug_en_11ab04_idx'), models.Index(fields=['status'], name='cms_page_status_3458bc_idx'), models.Index(fields=['published_at'], name='cms_page_publish_4a196c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordering', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('layout', models.CharField(default='default', max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(max_length=50)),
                ('settings', models.JSONField(default=dict)),
                ('ordering', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.section')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
