# Generated by Django 5.2 on 2026-08-08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_add_locale_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposerTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=255)),
                ("updated_by", models.CharField(blank=True, default="", max_length=255)),
                ("version", models.IntegerField(default=1)),
                (
                    "locale_updated_at",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Per-locale last-edit timestamps. Example: "
                            '{"fa": "2024-01-01T12:00:00Z", '
                            '"en": "2024-01-02T14:30:00Z"}'
                        ),
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("manifest", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft")],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "name"],
                        name="cms_compose_status_f6f0de_idx",
                    )
                ],
            },
        ),
    ]
