# Generated by Django 5.2.16 on 2026-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_composer_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template_variant',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
