# Generated by Django 5.2.16 on 2026-07-28 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('slug_fa', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('slug_en', models.SlugField(max_length=255, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('role_fa', models.CharField(blank=True, default='', max_length=255)),
                ('role_en', models.CharField(blank=True, default='', max_length=255)),
                ('client_fa', models.CharField(blank=True, default='', max_length=255)),
                ('client_en', models.CharField(blank=True, default='', max_length=255)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('technologies', models.JSONField(default=list)),
                ('outcome_fa', models.TextField(blank=True, default='')),
                ('outcome_en', models.TextField(blank=True, default='')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ManyToManyField(blank=True, related_name='portfolio_gallery', to='media.mediaasset')),
            ],
            options={
                'verbose_name_plural': 'case studies',
            },
        ),
        migrations.CreateModel(
            name='CaseStudyBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=2)),
                ('block_type', models.CharField(max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('ordering', models.IntegerField()),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_blocks', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['slug_fa'], name='portfolio_c_slug_fa_e408cb_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['slug_en'], name='portfolio_c_slug_en_b13616_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['status'], name='portfolio_c_status_56349f_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['published_at'], name='portfolio_c_publish_bdbaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['featured'], name='portfolio_c_feature_03120b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casestudyblock',
            unique_together={('case_study', 'locale', 'ordering')},
        ),
    ]
