# Generated by Django 5.2.16 on 2026-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='locale_updated_at',
            field=models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}'),
        ),
    ]
