# Generated by Django 5.2.16 on 2026-08-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_locale_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='problem_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='problem_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='statement_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='statement_fa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
