# Generated by Django 5.2.16 on 2026-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_casestudy_problem_en_casestudy_problem_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='limitations_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='limitations_fa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
