# Generated by Django 5.2.16 on 2026-07-28 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='workflow_au_content_43d055_idx'), models.Index(fields=['timestamp'], name='workflow_au_timesta_8f634d_idx'), models.Index(fields=['user'], name='workflow_au_user_id_59eaf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('object_id', models.UUIDField()),
                ('snapshot', models.JSONField()),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='workflow_re_content_ef5ce5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPublish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('scheduled_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publishes', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Scheduled Publish',
                'verbose_name_plural': 'Scheduled Publishes',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='workflow_sc_status_2545cc_idx'), models.Index(fields=['content_type', 'object_id'], name='workflow_sc_content_742658_idx')],
            },
        ),
    ]
