# Generated by Django 5.2.16 on 2026-07-28 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('object_id', models.UUIDField()),
                ('locale', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_tokens', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Preview Token',
                'verbose_name_plural': 'Preview Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='workflow_pr_token_86324e_idx'), models.Index(fields=['content_type', 'object_id'], name='workflow_pr_content_72c656_idx'), models.Index(fields=['expires_at'], name='workflow_pr_expires_125cf2_idx'), models.Index(fields=['revoked', 'expires_at'], name='workflow_pr_revoked_afb13d_idx')],
            },
        ),
    ]
