# Generated by Django 5.2.16 on 2026-07-28 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='media/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=64)),
                ('alt_text_fa', models.TextField(blank=True, default='')),
                ('alt_text_en', models.TextField(blank=True, default='')),
                ('caption_fa', models.TextField(blank=True, default='')),
                ('caption_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['mime_type'], name='media_media_mime_ty_c915f1_idx'), models.Index(fields=['status'], name='media_media_status_87acdc_idx'), models.Index(fields=['checksum'], name='media_media_checksu_dee3ba_idx')],
            },
        ),
    ]
