# Generated by Django 5.2.16 on 2026-07-29 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('organization_fa', models.CharField(max_length=255)),
                ('organization_en', models.CharField(max_length=255)),
                ('role_fa', models.CharField(blank=True, default='', max_length=255)),
                ('role_en', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('issuer_fa', models.CharField(max_length=255)),
                ('issuer_en', models.CharField(max_length=255)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-issued_on', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('institution_fa', models.CharField(max_length=255)),
                ('institution_en', models.CharField(max_length=255)),
                ('degree_fa', models.CharField(max_length=255)),
                ('degree_en', models.CharField(max_length=255)),
                ('field_fa', models.CharField(blank=True, default='', max_length=255)),
                ('field_en', models.CharField(blank=True, default='', max_length=255)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-ended_on', '-started_on', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('organization_fa', models.CharField(max_length=255)),
                ('organization_en', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('summary_fa', models.TextField(blank=True, default='')),
                ('summary_en', models.TextField(blank=True, default='')),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-started_on', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('name_fa', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('basic', 'basic'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('native', 'native')], max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
