# Generated by Django 5.2.16 on 2026-07-29 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_affiliation_certification_education_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('slug_fa', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('slug_en', models.SlugField(max_length=255, unique=True)),
                ('title_fa', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('abstract_fa', models.TextField(blank=True, default='')),
                ('abstract_en', models.TextField(blank=True, default='')),
                ('publication_type', models.CharField(choices=[('article', 'article'), ('book', 'book'), ('conference', 'conference'), ('report', 'report'), ('manuscript', 'manuscript')], max_length=20)),
                ('citation', models.TextField(blank=True, default='')),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('isbn', models.CharField(blank=True, default='', max_length=32)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-published_on', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('name_fa', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description_fa', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('slug_fa', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('slug_en', models.SlugField(max_length=255, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('summary_fa', models.TextField(blank=True, default='')),
                ('summary_en', models.TextField(blank=True, default='')),
                ('methodology_fa', models.TextField(blank=True, default='')),
                ('methodology_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
    ]
