# Generated by Django 5.2.16 on 2026-07-29 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_publication_researchinterest_researchproject'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('locale_updated_at', models.JSONField(blank=True, default=dict, help_text='Per-locale last-edit timestamps. Example: {"fa": "2024-01-01T12:00:00Z", "en": "2024-01-02T14:30:00Z"}')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label_fa', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255)),
                ('variant_type', models.CharField(choices=[('academic', 'academic'), ('industry', 'industry'), ('general', 'general')], max_length=20)),
                ('summary_fa', models.TextField(blank=True, default='')),
                ('summary_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume_variants', to='media.mediaasset')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
