# Generated by Django 5.2.16 on 2026-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_resumevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
